spring:
  profiles:
    active: # list
      -  dog
      -  EN
      -  dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcUrl: YmlUrl

--- # yml file separator
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcUrl: YmlProdUrl